---
title: "ESM 244 Lab 3 part 2 Kriging"
author: "Julia Cox"
format: 
  html:
    code-fold: show
    toc: true
    number-sections: true
    embed-resources: true
editor: visual
execute: 
  echo: true
  message: false
  warning: false
---

```{r}
library(tidyverse)
library(here)
library(sf) ##vector spatial data
library(terra) ## raster spatial data 
library(tidyterra) ## for rasters in ggplot
library(gstat)
library(stars)
library(abind)
```

# Overview 

Create a variogram in R ro understand the spatial dependende of ground water in California 

# Read in the data 

```{r}
ca_counties_sf <- read_sf(here("data/ca_counties"), layer = "CA_Counties_TIGER2016") %>%
  janitor::clean_names() %>%
  select(name)

ca_dgw_sf <- read_sf(here("data","ca_dgw",
                          'F2013_DBGS_Points_20150720_093252.gpkg')) %>% 
  janitor::clean_names()

#command-shift-c to toggle between comment and uncomment 
```


```{r}
ca_dgw_sf <- st_transform(ca_dgw_sf, 3857) %>% 
  rename(depth = dgbs)

ggplot() +
  geom_sf(data = ca_counties_sf) +
  geom_sf(data = ca_dgw_sf, aes(color = depth))


```

# Focus on San Joaquin County 

```{r}
sj_county_sf <- ca_counties_sf %>%
  filter(name == "San Joaquin")

sj_depth_sf <- ca_dgw_sf %>%
  st_intersection(sj_county_sf)

ggplot() +
  geom_sf(data = sj_county_sf) +
  geom_sf(data = sj_depth_sf, aes(color = depth)) +
  theme_void()

```

# Spatial Interpolation
## Make a variogram 

```{r}
sj_dgw_vgm <- gstat::variogram(depth ~ 1, data = sj_depth_sf) #no covariates, so put 1 
plot(sj_dgw_vgm)
#want to fit a line to this to get a function to use for predictions 

vgm_fit <- fit.variogram(sj_dgw_vgm,
                         model = vgm(model = "Gau", nugget = TRUE)) #gausian model to fit to the data
#adding a nugget makes line fit the variogram, tells it the intercept/nugget location 
plot(sj_dgw_vgm, vgm_fit)

attr(vgm_fit, "SSErr") #sum of squares error to compare the fit of the model 

```

# Spatial Kriging 

```{r}
sj_grid <- st_bbox(sj_county_sf) %>%
  stars::st_as_stars(dx = 1000, dy = 1000)

dgw_krige <- krige(depth ~ 1, sj_depth_sf, sj_grid, model = vgm_fit) #using regular kriging 

plot(dgw_krige)
```

```{r}
krige_rast <- dgw_krige %>% #turning it into raster data 
  terra::rast() %>%
  setNames(c("pred", "var"))

ggplot() +
  tidyterra::geom_spatraster(data = krige_rast, aes(fill = pred)) +
  geom_sf(data = sj_depth_sf, aes(fill = depth), shape = 21) +
  geom_sf(data = sj_county_sf, color = "black", fill = NA) + #compare obs to model 
  scale_fill_gradient(low = "blue", high = "yellow") + #points are filled with measured depth, bkgnd #filled with predicted depth 
  theme_minimal()

#same thing but looking at variance instead of predictions:
ggplot() +
  tidyterra::geom_spatraster(data = krige_rast, aes(fill = var)) + 
  geom_sf(data = sj_depth_sf, aes(fill = depth), shape = 21) +
  geom_sf(data = sj_county_sf, color = "black", fill = NA) + 
  scale_fill_gradient(low = "blue", high = "yellow") +
  theme_minimal()


```













